### PR TITLE
feat: extra headers

### PR DESCRIPTION
**Pull request by theus77**
Add extra security headers to the solution
This PR introduce has regression as those headers add restrictions. I.e. the Content-Security-Policy header forces to use https
This PR also fixes

- the fact the Cache-Control is currently set twice (once by Symfony and once by Apache
- the fact that Symfony can't override Symfony headers

### CODE REVIEW

**Review by zebby76 — APPROVED** [review]

**Review by zebby76 — CHANGES_REQUESTED** [review]
The script is broken, you forgot to close each tests ( if ... fi )

**Comment by theus77** [comment]
> The script is broken, you forgot to close each tests ( if ... fi )

Thanks, you saved me times

**Comment by zebby76** [comment]
> > The script is broken, you forgot to close each tests ( if ... fi )
> 
> Thanks, you saved me times

About the build failure, I suggest to update the docker-compose file to change the name of the Docker image of the used admin.  There are 2 versions in parrallel (1.x and 4.x) and using the 'latest' tag will take the last built version (and maybe not the one you want).  For example, currently, we test a 3.x skeleton with a 4.x admin version -> broken .

This can save also your time :-)

**Review by zebby76 — APPROVED** [review]

**Comment by Davidmattei** [comment]
👍

**Review by Davidmattei — APPROVED** [review]

**Pull request merged**
